%% plot_fk_update_illustration.m
% -------------------------------------------------------------------------
% Illustration of discrete free-convection (FK) update in TPPS model
%
% Left : Temperature profile T(z) at multiple time levels
% Right: Geometrically scaled TPPS cross-section with temperature coloring
%
% The blue patch indicates the discrete FK update region
% (z_lower_bypass <= z <= z_membrane).
%
% Author: autogenerated with ChatGPT
% -------------------------------------------------------------------------

clear; clc; close all;

%% ------------------------------------------------------------------------
% 1) Geometric parameters (all lengths in meters)
% -------------------------------------------------------------------------
H_tot = 10.0;              % total water height

z_inlet        = 9.5;
z_upper_bypass = 8.0;
z_upper_rep    = 7.5;
z_membrane     = 5.0;
z_lower_bypass = 4.5;
z_lower_rep    = 4.0;
z_outlet       = 0.0;

z_marks = [ ...
    z_inlet
    z_upper_bypass
    z_upper_rep
    z_membrane
    z_lower_bypass
    z_lower_rep
    z_outlet ];

z_labels = { ...
    'z_{inlet}'
    'z_{upper bypass}'
    'z_{upper rep}'
    'z_{membrane}'
    'z_{lower bypass}'
    'z_{lower rep}'
    'z_{outlet}' };


%% ------------------------------------------------------------------------
% 2) Vertical grid
% -------------------------------------------------------------------------
Nz = 500;
z  = linspace(z_outlet, z_inlet, Nz).';

%% ------------------------------------------------------------------------
% 3) Piecewise temperature profile T^n(z)
% -------------------------------------------------------------------------
Tn = zeros(size(z));

% --- Segment D: lower volume (almost isothermal) ---
Tn(z <= z_lower_rep) = 45;

% --- Segment C: weak gradient (lower bypass region) ---
idx_C = z > z_lower_rep & z <= z_lower_bypass;
Tn(idx_C) = linspace(45, 47, sum(idx_C));

% --- Segment B: upper bypass region (weak response due to advection) ---
idx_B = z > z_lower_bypass & z <= z_upper_bypass;
Tn(idx_B) = linspace(47, 55, sum(idx_B));

% --- Segment A: upper volume (strong gradient up to inlet profile temp) ---
idx_A = z > z_upper_bypass & z <= z_inlet;
Tn(idx_A) = linspace(55, 65, sum(idx_A));

% Inlet boundary condition (not part of energy content)
T_inlet = 80;

%% ------------------------------------------------------------------------
% 4) Qualitative later time profiles
% -------------------------------------------------------------------------
% Slight right-shift above upper bypass, almost unchanged below
shift1 = 2.0 * exp(-((z - z_upper_bypass)/1.2).^2);
shift2 = 3.5 * exp(-((z - z_upper_bypass)/1.2).^2);

Tn_dt  = Tn + shift1;
Tn_2dt = Tn + shift2;

%% ------------------------------------------------------------------------
% 5) FK update region as trapezoid (aligned to T^n)
% -------------------------------------------------------------------------
idx_fk = z >= z_lower_bypass & z <= z_membrane;

T_fk_top = Tn(idx_fk);
T_fk_bot = T_fk_top - 4.0;   % width of trapezoid (visual, schematic)

z_fk = z(idx_fk);

%% ------------------------------------------------------------------------
% 3) Figure & layout (shared z-axis)
% -------------------------------------------------------------------------
figure('Color','w','Position',[100 100 1200 700]);

tiledlayout(1,2,'TileSpacing','compact','Padding','compact');

%% ------------------------------------------------------------------------
% 4) LEFT: z–T diagram
% -------------------------------------------------------------------------
ax1 = nexttile;
hold on; box on; grid on;

plot(Tn,    z, 'k',  'LineWidth',2);
plot(Tn_dt, z, 'Color',[0.5 0.5 0.5],'LineWidth',2);
plot(Tn_2dt,z, 'Color',[0.8 0.8 0.8],'LineWidth',2);

% FK update region (blue patch)

% FK patch (drawn first)
patch([T_fk_top; flipud(T_fk_bot)], ...
      [z_fk;     flipud(z_fk)], ...
      [0.8 0.9 1.0], ...
      'EdgeColor','none','FaceAlpha',0.45);

% horizontal reference lines
for i = 1:numel(z_marks)
    yline(z_marks(i),'k:');
end

xlabel('Temperature T [^\circC]');
ylabel('Height z [m]');
title('Temperature evolution and FK update region');

legend({'T^n','T^{n+\Delta t}','T^{n+2\Delta t}','Discrete FK update'}, ...
       'Location','southoutside');

ylim([z_outlet z_inlet]);

%% ------------------------------------------------------------------------
% 5) RIGHT: TPPS cross-section (scaled in z)
% -------------------------------------------------------------------------
ax2 = nexttile;
hold on; box on;

% geometric widths (arbitrary but fixed)
w_core   = 1.0;
w_gap    = 0.3;
x0       = 0.0;

% temperature colormap
cmap = jet(256);
colormap(ax2,cmap);

% draw water column as colored rectangles
for i = 1:Nz-1
    dz_loc = z(i+1) - z(i);
    Tloc   = T_n(i);
    cidx   = round(1 + (Tloc-45)/(80-45)*(size(cmap,1)-1));
    cidx   = max(min(cidx,size(cmap,1)),1);
    
    rectangle('Position',[x0, z(i), w_core, dz_loc], ...
              'FaceColor',cmap(cidx,:), ...
              'EdgeColor','none');
end

% membrane
plot([x0 x0+w_core],[z_membrane z_membrane],'k','LineWidth',2);
text(x0+w_core+0.05,z_membrane,'membrane','VerticalAlignment','bottom');

% bypass openings
plot([x0+w_core x0+w_core+w_gap],[z_upper_bypass z_upper_bypass],'k','LineWidth',2);
plot([x0+w_core x0+w_core+w_gap],[z_lower_bypass z_lower_bypass],'k','LineWidth',2);

text(x0+w_core+w_gap+0.05,z_upper_bypass,'upper bypass','VerticalAlignment','middle');
text(x0+w_core+w_gap+0.05,z_lower_bypass,'lower bypass','VerticalAlignment','middle');

% residual energy box
rectangle('Position',[x0+w_core+w_gap+0.6, z_lower_bypass+0.3, 1.6, 1.0], ...
          'EdgeColor','k','LineWidth',1.5);
text(x0+w_core+w_gap+0.65,z_lower_bypass+0.9, ...
    {'Residual thermal energy','stored for discrete FK update'}, ...
    'FontSize',9);

annotation('arrow', ...
    [0.77 0.85],[0.55 0.55]);

axis equal;
xlim([-0.2 4.0]);
ylim([z_outlet z_inlet]);

xlabel('Radial direction (schematic)');
title('TPPS cross-section and algorithmic interpretation');

cb = colorbar;
cb.Label.String = 'Temperature [^\circC]';

linkaxes([ax1 ax2],'y');

%% ------------------------------------------------------------------------
% End of script
% -------------------------------------------------------------------------
